name: seti
description: Seti file icons for different file types, auto detected by file name.
version: 0.1.0
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/pd4d10/seti-flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0
  dart_style: ^1.2.10

flutter:
  fonts:
    - family: Seti
      fonts:
        - asset: fonts/seti.ttf
